[[headers]]
  for = "/*.(js|mjs|cjs|jsx)"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*.(json|map)"
  [headers.values]
    Content-Type = "application/json" 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 
  