# Create a netlify.toml file in your project root

[build]
  # Directory to change to before starting a build
  # If you're using a monorepo, specify the path to your app
  base = "/"  # Update this if your project is in a subdirectory
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "dist"  # This should match Vite's build output directory
  
  # Default build command
  command = "npm run build"

# If you need environment variables
[build.environment]
  NODE_VERSION = "18"  # Specify Node version